### PR TITLE
ci: remove superfluous yarn installation step

### PR DESCRIPTION
**Pull request by PaulRBerg**
First, this PR removes the superfluous yarn installation step from the CI workflow. The [setup-node](https://github.com/actions/setup-node) action automatically installs npm and yarn globally.

Second, this PR activates the [caching functionality](https://github.com/actions/setup-node#caching-packages-dependencies) of the `setup-node` GitHub Action by setting the `cache` field.

### CODE REVIEW

**Comment by cleanunicorn** [comment]
The build seems to fail with this config. Also running this on my local machine with [`act`](https://github.com/nektos/act) outputs this error.

```
$ act
[Tests/tests] 🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
[Tests/tests]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=false
[Tests/tests]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Tests/tests]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Tests/tests]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[Tests/tests]   🐳  docker cp src=/home/daniel/Development/github.com/cleanunicorn/ethereum-smartcontract-template/. dst=/home/daniel/Development/github.com/cleanunicorn/ethereum-smartcontract-template
[Tests/tests]   🐳  docker exec cmd=[mkdir -p /home/daniel/Development/github.com/cleanunicorn/ethereum-smartcontract-template] user= workdir=
[Tests/tests] ⭐  Run Install Foundry
[Tests/tests]   ☁  git clone 'https://github.com/onbjerg/foundry-toolchain' # ref=v1.0.6
[Tests/tests]   🐳  docker cp src=/home/daniel/.cache/act/onbjerg-foundry-toolchain@v1.0.6/ dst=/var/run/act/actions/onbjerg-foundry-toolchain@v1.0.6/
[Tests/tests]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/onbjerg-foundry-toolchain@v1.0.6/] user= workdir=
[Tests/tests]   🐳  docker exec cmd=[node /var/run/act/actions/onbjerg-foundry-toolchain@v1.0.6/dist/index.js] user= workdir=
[Tests/tests]   💬  ::debug::Downloading https://github.com/gakonst/foundry/releases/download/nightly/foundry_nightly_linux_amd64.tar.gz
[Tests/tests]   💬  ::debug::Destination /tmp/6787be9e-8eb2-46e5-bd6a-4317e221dffc
[Tests/tests]   💬  ::debug::download complete
[Tests/tests]   💬  ::debug::Checking tar --version
[Tests/tests]   💬  ::debug::tar (GNU tar) 1.30%0ACopyright (C) 2017 Free Software Foundation, Inc.%0ALicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.%0AThis is free software: you are free to change and redistribute it.%0AThere is NO WARRANTY, to the extent permitted by law.%0A%0AWritten by John Gilmore and Jay Fenlason.
| [command]/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /tmp/f4ae6a74-47b7-44fe-916a-7e9f3ec6b1d4 -f /tmp/6787be9e-8eb2-46e5-bd6a-4317e221dffc
[Tests/tests]   ✅  Success - Install Foundry
[Tests/tests] ⭐  Run Install node
[Tests/tests]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v2
[Tests/tests]   🐳  docker cp src=/home/daniel/.cache/act/actions-setup-node@v2/ dst=/var/run/act/actions/actions-setup-node@v2/
[Tests/tests]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/actions-setup-node@v2/] user= workdir=
[Tests/tests]   🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-node@v2/dist/setup/index.js] user= workdir=
[Tests/tests]   💬  ::debug::isExplicit: 
[Tests/tests]   💬  ::debug::explicit? false
[Tests/tests]   💬  ::debug::isExplicit: 12.22.11
[Tests/tests]   💬  ::debug::explicit? true
[Tests/tests]   💬  ::debug::isExplicit: 16.14.2
[Tests/tests]   💬  ::debug::explicit? true
[Tests/tests]   💬  ::debug::evaluating 0 versions
[Tests/tests]   💬  ::debug::match not found
| Attempting to download 16...
[Tests/tests]   💬  ::debug::No manifest cached
[Tests/tests]   💬  ::debug::Getting manifest from actions/node-versions@main
[Tests/tests]   💬  ::debug::check 16.14.2 satisfies 16
[Tests/tests]   💬  ::debug::x64===x64 && darwin===linux
[Tests/tests]   💬  ::debug::x64===x64 && linux===linux
[Tests/tests]   💬  ::debug::matched 16.14.2
| Acquiring 16.14.2 - x64 from https://github.com/actions/node-versions/releases/download/16.14.2-2007501289/node-16.14.2-linux-x64.tar.gz
[Tests/tests]   💬  ::debug::Downloading https://github.com/actions/node-versions/releases/download/16.14.2-2007501289/node-16.14.2-linux-x64.tar.gz
[Tests/tests]   💬  ::debug::Destination /tmp/549c61b9-5303-44af-ace8-09ba983da011
[Tests/tests]   💬  ::debug::download complete
| Extracting ...
[Tests/tests]   💬  ::debug::Checking tar --version
[Tests/tests]   💬  ::debug::tar (GNU tar) 1.30%0ACopyright (C) 2017 Free Software Foundation, Inc.%0ALicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.%0AThis is free software: you are free to change and redistribute it.%0AThere is NO WARRANTY, to the extent permitted by law.%0A%0AWritten by John Gilmore and Jay Fenlason.
| [command]/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /tmp/be199496-932d-48a7-bcbd-0e65087226be -f /tmp/549c61b9-5303-44af-ace8-09ba983da011
| Adding to the cache ...
[Tests/tests]   💬  ::debug::Caching tool node 16.14.2 x64
[Tests/tests]   💬  ::debug::source dir: /tmp/be199496-932d-48a7-bcbd-0e65087226be
[Tests/tests]   💬  ::debug::destination /opt/hostedtoolcache/node/16.14.2/x64
[Tests/tests]   💬  ::debug::finished caching tool
| Done
[Tests/tests]   ❗  ::error::Unable to locate executable file: yarn. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[Tests/tests]   ❌  Failure - Install node
[Tests/tests] exit with `FAILURE`: 1
Error: Job 'tests' failed
```

This is the change I did locally

```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index b805112..f828abd 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,14 +16,17 @@ jobs:
 
       - name: Install node
         uses: actions/setup-node@v2
+        with:
+          cache: yarn
+          node-version: 16
 
       - name: Clone repo with submodules
         uses: actions/checkout@v2
         with:
           submodules: recursive
 
-      - name: Install yarn
-        run: npm i -g yarn
+      # - name: Install yarn
+      #   run: npm i -g yarn
 
       - name: Install dependencies
         run: make

```

**Comment by PaulRBerg** [comment]
Very odd! In my personal GitHub workflows Yarn works just fine without this step. Perhaps it's something that they added in v2, not sure .. this repo uses v1.

**Comment by cleanunicorn** [comment]
> Very odd! In my personal GitHub workflows Yarn works just fine without this step. Perhaps it's something that they added in v2, not sure .. this repo uses v1.

I see this failing in your case with the same error.

https://github.com/paulrberg/ethereum-smartcontract-template/actions/runs/2084620175

**Comment by cleanunicorn** [comment]
What would entail upgrading to v2?

**Comment by PaulRBerg** [comment]
By "personal", I meant personal repos. Not my fork of this template.

> What would entail upgrading to v2?

Only good things! Yarn v3 is faster, more extensible, and more user-friendly. [Migrating](https://yarnpkg.com/getting-started/migration) is easy-peasy. You can see how I use it [here](https://github.com/paulrberg/solidity-template/blob/7eed7a53745bf810dbba08d70cbff10cca5afd22/.yarnrc.yml).

**Comment by cleanunicorn** [comment]
Not sure what I am doing wrong

https://github.com/cleanunicorn/ethereum-smartcontract-template/tree/feat/upgrade-yarn-v2

**Comment by PaulRBerg** [comment]
I think this has something to do with the GitHub Actions cache. And unfortunately, the cache [cannot be manually deleted](https://github.community/t/how-to-clear-cache-in-github-actions/129038/8) (*cough cough* GitHub when are you going to add support for this!?).

Your integration of the latest version of Yarn LGTM. I'm certain that it shouldn't be necessary to install Yarn manually! [My PRBMath CI](https://github.com/paulrberg/prb-math/blob/426aa3d0e1d2d5f26a3118d130ccc1b7a3d0cf4a/.github/workflows/integration.yaml#L25-L32) works without it.

At any rate - one cool plugin you might be interested in taking for a spin is [interactive-tools](https://yarnpkg.com/api/modules/plugin_interactive_tools.html):

```bash
$ yarn plugin import interactive-tools
```

And run it like this:

```bash
$ yarn upgrade-interactive
```

You will absolutely love it :)

**Comment by cleanunicorn** [comment]
Archiving this until we find a fix

**Pull request closed without merging**
